# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUserlogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_userlogin(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(1721, 1033)
    self.driver.find_element(By.LINK_TEXT, "Join/Log in").click()
    self.driver.find_element(By.ID, "username_or_email").send_keys("user123")
    self.driver.find_element(By.ID, "password").send_keys("user1234")
    self.driver.find_element(By.ID, "username_or_email").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".auth-button").click()
  
