# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdvancedsearch():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_advancedsearch(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(1721, 1033)
    self.driver.find_element(By.LINK_TEXT, "高级搜索").click()
    self.driver.find_element(By.CSS_SELECTOR, ".filter-group > select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".filter-group > select")
    dropdown.find_element(By.XPATH, "//option[. = '宾夕法尼亚大学']").click()
    self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(2) > option:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".filter-row:nth-child(1) input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".filter-row:nth-child(1) input").send_keys("杯")
    self.driver.find_element(By.CSS_SELECTOR, ".filter-row:nth-child(2) > .filter-group:nth-child(1) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".filter-row:nth-child(2) > .filter-group:nth-child(1) > input").send_keys("1500-1600")
    self.driver.find_element(By.CSS_SELECTOR, "textarea").click()
    self.driver.find_element(By.CSS_SELECTOR, "textarea").send_keys("青花瓷")
    self.driver.find_element(By.CSS_SELECTOR, ".search-btn").click()
  
