# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTimeline():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_timeline(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(1721, 1033)
    self.driver.find_element(By.LINK_TEXT, "时间轴").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, ".tl-slidenav-next > .tl-slidenav-content-container").click()
    self.driver.find_element(By.CSS_SELECTOR, ".tl-slidenav-next .tl-slidenav-description").click()
    self.driver.find_element(By.CSS_SELECTOR, ".tl-slidenav-next .tl-slidenav-description").click()
    self.driver.find_element(By.CSS_SELECTOR, ".tl-slidenav-next .tl-slidenav-description").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".tl-slidenav-next span:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".tl-slidenav-next span:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".tl-slidenav-next span:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".tl-slidenav-next span:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".tl-slidenav-next span:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".tl-slidenav-next span:nth-child(1)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".tl-slidenav-next span:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#tl-pavlb-marker .tl-headline").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tl-pmawcv-marker .tl-headline").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tl-qndoz-marker .tl-timemarker-content").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tl-pavlb-marker .tl-headline").click()
    self.driver.find_element(By.CSS_SELECTOR, "#\\--2-marker .tl-timemarker-content").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tl-ymzwus-marker .tl-headline").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tl-yyokg-marker .tl-timemarker-content").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tl-qwkihp-marker .tl-icon-image").click()
  
