# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchByLib11():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchByLib11(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(1721, 1033)
    self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(1)").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(1)")
    dropdown.find_element(By.XPATH, "//option[. = '博物馆']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    self.driver.execute_script("window.scrollTo(0,295.3333435058594)")
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("人类")
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys(Keys.ENTER)
    self.driver.execute_script("window.scrollTo(0,744)")
  
