# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchByArtist111():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchByArtist111(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(1721, 1033)
    self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(1)").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "select:nth-child(1)")
    dropdown.find_element(By.XPATH, "//option[. = '艺术家']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("孙")
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".search-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gallery-item:nth-child(1) img").click()
  
