# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMappingknowledgedomain():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mappingknowledgedomain(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(1721, 1033)
    self.driver.find_element(By.LINK_TEXT, "知识图谱").click()
    self.driver.find_element(By.CSS_SELECTOR, "select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "select")
    dropdown.find_element(By.XPATH, "//option[. = '大都会博物馆']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".all-tag").click()
    self.driver.find_element(By.CSS_SELECTOR, ".option-section:nth-child(1) .tag:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".option-section:nth-child(1) .tag:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".option-section:nth-child(1) .tag:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".all-tag").click()
    self.driver.find_element(By.CSS_SELECTOR, ".option-section:nth-child(2) .tag:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".option-section:nth-child(2) .tag:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".option-section:nth-child(2) .tag:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "select")
    dropdown.find_element(By.XPATH, "//option[. = '宾夕法尼亚大学考古与人类学博物馆']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".option-section:nth-child(1) .tag:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".all-tag").click()
    self.driver.find_element(By.CSS_SELECTOR, "select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "select")
    dropdown.find_element(By.XPATH, "//option[. = '大都会博物馆']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(1) > text").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(6) > circle").click()
    self.driver.find_element(By.CSS_SELECTOR, ".graph > svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".option-section:nth-child(1) .tag:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(9) > text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".option-section:nth-child(1) .tag:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(1) > text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".option-section:nth-child(2) .tag:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".option-section:nth-child(2) .tag:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(6) > text").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(3) > text").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(2) > text").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(12) > text").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(15) > text").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(4) > circle").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(26) > circle").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(18) > text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".option-section:nth-child(2) .tag:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "g:nth-child(2) > circle").click()
    self.driver.find_element(By.CSS_SELECTOR, ".option-section:nth-child(1) .tag:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".all-tag").click()
    self.driver.find_element(By.CSS_SELECTOR, ".download-btn").click()
    self.driver.close()
  
